import React, { useEffect, useState } from 'react';
import {
  Target,
  CheckCircle2,
  XCircle,
  Brain,
  Send,
  Sparkles,
  HelpCircle,
  Check,
  User,
} from 'lucide-react';
import { api } from '../services/api';
import { FollowUpQuestion, FollowUpAttempt, Student, CreateFollowUpAttemptPayload } from '../types/api';
import { Badge } from '../components/common/Badge';
import { LoadingSpinner, ErrorState, EmptyState } from '../components/common/FeedbackStates';
import { Modal } from '../components/common/Modal';

export const RemediationCenterPage: React.FC = () => {
  const [followUpQuestions, setFollowUpQuestions] = useState<FollowUpQuestion[]>([]);
  const [followUpAttempts, setFollowUpAttempts] = useState<FollowUpAttempt[]>([]);
  const [students, setStudents] = useState<Student[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Active Remediation Question to Solve
  const [activeQuestion, setActiveQuestion] = useState<FollowUpQuestion | null>(null);
  const [selectedStudentId, setSelectedStudentId] = useState<number | null>(null);
  const [answer, setAnswer] = useState('');
  const [reasoning, setReasoning] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitFeedback, setSubmitFeedback] = useState<string | null>(null);

  const loadData = async () => {
    setLoading(true);
    setError(null);
    try {
      const [fqRes, faRes, studentsRes] = await Promise.all([
        api.getFollowUpQuestions(),
        api.getFollowUpAttempts(),
        api.getStudents(),
      ]);

      const fqList = fqRes.data || [];
      const faList = faRes.data || [];
      const sList = studentsRes.data || [];

      setFollowUpQuestions(fqList);
      setFollowUpAttempts(faList);
      setStudents(sList);

      if (sList.length > 0) setSelectedStudentId(sList[0].student_id);
    } catch (err: any) {
      setError(err.message || 'Failed to load remediation data from MySQL');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  const handleOpenSolve = (q: FollowUpQuestion) => {
    setActiveQuestion(q);
    setAnswer('');
    setReasoning('');
    setSubmitFeedback(null);
  };

  const handleSolveSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!activeQuestion || !selectedStudentId || !answer.trim()) return;

    setIsSubmitting(true);
    setSubmitFeedback(null);
    try {
      const payload: CreateFollowUpAttemptPayload = {
        followup_id: activeQuestion.followup_id,
        attempt_id: 1, // Fallback attempt reference
        student_id: selectedStudentId,
        answer: answer.trim(),
        reasoning: reasoning.trim() || undefined,
        is_correct: true,
      };

      await api.createFollowUpAttempt(payload);
      setSubmitFeedback('Remediation attempt recorded successfully!');
      
      // Reload attempts
      const updatedAttempts = await api.getFollowUpAttempts();
      setFollowUpAttempts(updatedAttempts.data || []);
      
      setTimeout(() => {
        setActiveQuestion(null);
      }, 1500);
    } catch (err: any) {
      setSubmitFeedback(`Submission error: ${err.message}`);
    } finally {
      setIsSubmitting(false);
    }
  };

  if (loading) {
    return <LoadingSpinner message="Loading Remediation Center & Follow-up Pathways..." size="lg" />;
  }

  if (error) {
    return <ErrorState title="Remediation Center Unavailable" message={error} onRetry={loadData} />;
  }

  return (
    <div className="space-y-8 max-w-6xl mx-auto animate-fadeIn">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4 pb-4 border-b border-slate-800">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-xl font-extrabold text-white tracking-tight">
              Remediation Center
            </h2>
            <Badge variant="indigo" size="md">
              {followUpQuestions.length} Follow-up Questions
            </Badge>
          </div>
          <p className="text-xs text-slate-400">
            Targeted remediation pathways generated by Groq AI to test and resolve diagnosed misconceptions.
          </p>
        </div>
      </div>

      {/* Grid: Follow-Up Questions List */}
      <div className="space-y-4">
        <h3 className="text-sm font-bold text-slate-300 uppercase tracking-wider flex items-center gap-2">
          <Target className="w-4 h-4 text-indigo-400" />
          <span>Active Remediation Questions ({followUpQuestions.length})</span>
        </h3>

        {followUpQuestions.length === 0 ? (
          <EmptyState
            icon={<Target className="w-10 h-10 text-slate-500" />}
            title="No Remediation Questions Yet"
            description="When misconceptions are diagnosed during practice attempts, targeted follow-up remediation questions will appear here."
          />
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {followUpQuestions.map((q) => (
              <div
                key={q.followup_id}
                className="glass-panel p-5 rounded-2xl border border-slate-800 space-y-4 flex flex-col justify-between hover:border-slate-700 transition-all"
              >
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <span className="text-[10px] font-extrabold text-indigo-400 uppercase tracking-wider">
                      Follow-up #{q.followup_id}
                    </span>
                    <Badge variant={q.difficulty === 'Easy' ? 'emerald' : q.difficulty === 'Medium' ? 'amber' : 'rose'} size="sm">
                      {q.difficulty || 'Easy'}
                    </Badge>
                  </div>

                  <div>
                    <h4 className="text-sm font-bold text-white leading-relaxed">
                      {q.question_text}
                    </h4>
                    {q.expected_concept && (
                      <p className="text-xs text-slate-400 mt-2 font-mono">
                        Target Concept: <span className="text-indigo-300">{q.expected_concept}</span>
                      </p>
                    )}
                  </div>

                  {q.misconception_type && (
                    <div className="flex gap-2">
                      <Badge variant="rose" size="sm">
                        Fixes: {q.misconception_type}
                      </Badge>
                    </div>
                  )}
                </div>

                <div className="pt-3 border-t border-slate-800 flex justify-end">
                  <button
                    onClick={() => handleOpenSolve(q)}
                    className="px-3.5 py-1.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold uppercase tracking-wider transition-all flex items-center gap-1.5 shadow-md shadow-indigo-600/20"
                  >
                    <span>Solve Question</span>
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Feed: Follow-up Resolution Attempts */}
      <div className="glass-panel p-6 rounded-2xl border border-slate-800 space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-emerald-400" />
            <span>Remediation Attempt Log ({followUpAttempts.length})</span>
          </h3>
          <span className="text-xs text-slate-500 font-mono">Real-time resolution history</span>
        </div>

        {followUpAttempts.length === 0 ? (
          <div className="p-8 text-center text-xs text-slate-400">
            No remediation attempts recorded yet. Click "Solve Question" above to log the first remediation attempt.
          </div>
        ) : (
          <div className="divide-y divide-slate-800">
            {followUpAttempts.map((fa) => (
              <div key={fa.followup_attempt_id} className="py-3 flex flex-wrap items-center justify-between gap-3 text-xs">
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <User className="w-3.5 h-3.5 text-indigo-400" />
                    <span className="font-bold text-white">{fa.student_name || `Student #${fa.student_id}`}</span>
                    <Badge variant="indigo" size="sm">Follow-up #{fa.followup_id}</Badge>
                  </div>
                  <p className="text-slate-300 font-mono text-[11px]">
                    Answer: <span className="font-bold text-white">"{fa.answer}"</span>
                    {fa.reasoning && <> • Reasoning: "{fa.reasoning}"</>}
                  </p>
                </div>

                <div className="flex items-center gap-2">
                  <Badge variant={fa.is_correct ? 'emerald' : 'amber'} size="sm">
                    {fa.is_correct ? 'Concept Resolved' : 'Attempted'}
                  </Badge>
                  <span className="text-slate-500 text-[11px]">
                    {new Date(fa.timestamp).toLocaleDateString()}
                  </span>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Interactive Solve Modal */}
      {activeQuestion && (
        <Modal
          isOpen={Boolean(activeQuestion)}
          onClose={() => setActiveQuestion(null)}
          title={`Remediation Question #${activeQuestion.followup_id}`}
          subtitle="Prove conceptual understanding by solving this targeted question."
        >
          <form onSubmit={handleSolveSubmit} className="space-y-4 text-xs">
            <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 space-y-2">
              <span className="font-bold text-indigo-400 uppercase tracking-wider block">
                Target Question:
              </span>
              <p className="text-sm font-semibold text-white">
                {activeQuestion.question_text}
              </p>
              {activeQuestion.expected_concept && (
                <p className="text-slate-400">
                  Concept: <span className="text-indigo-300">{activeQuestion.expected_concept}</span>
                </p>
              )}
            </div>

            <div>
              <label className="block font-bold text-slate-300 uppercase tracking-wider mb-1">
                Select Student:
              </label>
              <select
                value={selectedStudentId || ''}
                onChange={(e) => setSelectedStudentId(Number(e.target.value))}
                className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3.5 py-2 text-xs text-white focus:outline-none focus:border-indigo-500"
              >
                {students.map((s) => (
                  <option key={s.student_id} value={s.student_id}>
                    {s.name} ({s.email})
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block font-bold text-slate-300 uppercase tracking-wider mb-1">
                Your Answer: <span className="text-rose-400">*</span>
              </label>
              <input
                type="text"
                required
                value={answer}
                onChange={(e) => setAnswer(e.target.value)}
                placeholder="Enter answer..."
                className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3.5 py-2 text-xs text-white font-mono placeholder-slate-500 focus:outline-none focus:border-indigo-500"
              />
            </div>

            <div>
              <label className="block font-bold text-slate-300 uppercase tracking-wider mb-1">
                Reasoning (Explain corrected approach):
              </label>
              <textarea
                rows={2}
                value={reasoning}
                onChange={(e) => setReasoning(e.target.value)}
                placeholder="Explain how you applied the concept correctly..."
                className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3.5 py-2 text-xs text-white font-mono placeholder-slate-500 focus:outline-none focus:border-indigo-500 resize-none"
              />
            </div>

            {submitFeedback && (
              <div className={`p-3 rounded-xl border text-xs font-semibold ${
                submitFeedback.includes('error')
                  ? 'bg-rose-950/50 border-rose-500/30 text-rose-300'
                  : 'bg-emerald-950/50 border-emerald-500/30 text-emerald-300'
              }`}>
                {submitFeedback}
              </div>
            )}

            <div className="pt-2 flex justify-end gap-3">
              <button
                type="button"
                onClick={() => setActiveQuestion(null)}
                className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 font-semibold transition-all"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={isSubmitting || !answer.trim()}
                className="px-5 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold uppercase tracking-wider transition-all disabled:opacity-50 flex items-center gap-2"
              >
                {isSubmitting ? (
                  <span>Saving...</span>
                ) : (
                  <>
                    <Send className="w-3.5 h-3.5" />
                    <span>Submit Remediation</span>
                  </>
                )}
              </button>
            </div>
          </form>
        </Modal>
      )}
    </div>
  );
};
